---

devices:
  R1:
    ipv6:
      enabled: True
      ospfv3:
        id:
          - "1"
    interfaces:
      - type: "GigabitEthernet"
        number: "2"
        description: "TO Webserver"
        ipv6_prefix: 
          - "2001:420:4021:1710::1/64"
        nd_prefix: "2001:420:4021:1710::/64"
      - type: "GigabitEthernet"
        number: "5"
        description: "TO R2"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"

  R2:
    ipv6:
      enabled: True
      ospfv3:
        id:
          - "1"
    interfaces:
      - type: "GigabitEthernet"
        number: "4"
        description: "TO R1"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"
      - type: "GigabitEthernet"
        number: "5"
        description: "TO Finland"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"
      - type: "GigabitEthernet"
        number: "6"
        description: "TO Japan"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"

  R3:
    ipv6:
      enabled: True
      ospfv3:
        id:
          - "1"
    interfaces:
      - type: "GigabitEthernet"
        number: "4"
        description: "TO R2"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"
      - type: "GigabitEthernet"
        number: "5"
        description: "TO Finland office"
        ipv6_prefix:
          - "2001:420:4021:1720::1/64"
        nd_prefix: "2001:420:4021:1720::/64"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"

  R4:
    ipv6:
      enabled: True
      ospfv3:
        id:
          - "1"
    interfaces:
      - type: "GigabitEthernet"
        number: "4"
        description: "TO R2"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"
      - type: "GigabitEthernet"
        number: "5"
        description: "TO Japan office"
        ipv6_prefix:
          - "2001:420:4021:1730::1/64"
        nd_prefix: "2001:420:4021:1730::/64"
        ospfv3:
          process_id: "1"
          process_area: "0"
          priority: "0"
